liuchengxu/vim-which-key

autoload/which_key/window.vim

In my case there is some option or plugin that enables `number` and `relativenumber` in which_key window. So I have to un-`setlocal` them explicitly.
Maybe there is better approach, I'm not that proficient with VimL and there is probably a better way to do this.

Completely disable numbers in which_key window

---

autoload/which_key.vim

The original command exist(':'.Cmd) is not valid.

fix bug: recognize ':' successfully.

---

README.md

vim-plug on-demand which_key#register wrong spell, missing _key

Fix README command spell

---

autoload/which_key.vim

`:WhichKey! g:which_key_map` doesn't seem to be working.
I'm getting error on nvim 0.4:
`E735: Can only compare Dictionary with Dictionary`
`E15: Invalid expression: key ==# ' ' ? 'SPC' : key`
and then another error:
`E121: Undefined variable: s:which_key_trigger`

Fix WhichKey! with dictionary argument.

---

README.md

README minor spelling

---

autoload/which_key/view.vim
doc/vim-which-key.txt

This will allow the user to define their own symbols. For example
```
let g:which_key_display_names = {
\ ' '         : '□'      ,
\ '<CR>'      : '↵'      ,
\ '<BS>'      : '⌫'      ,
\ '<TAB>'     : '⇆'      ,
\ '<C-SPACE>' : 'Ctrl-□' ,
\ }
```
would give something like this

Allow user provided key symbols

---

syntax/which_key.vim

Fixes the syntax highlighting for key symbols longer than 3 characters.
Old
New

Fix syntax regex for longer key symbols

---

autoload/which_key.vim
autoload/which_key/util.vim

Support Alt mappings, as well as Ctrl+Space. getchar returns a string of the input in that case, instead of a character number, so nr2char doesn't work for them.
My solution doesn't support all possible inputs (for example inputs with accents <M-à>, etc), but this should be good enough for most people.

Add support for special characters

---

autoload/which_key/view.vim

Fixing the calculation of the max element length
Old: Note that the computed width for the "s" mapping (3rd from the bottom) isn't large enough to hold the entire description. This is because the maxlength currently doesn't account for the padding at the beginning of the line
New

Compute symbol and description lengths separately

---

ftplugin/which_key.vim

Sometimes other plugins would like to parse keybindings as folds, such as the following image.
This patch avoids these folds.

Disable foldenable option for the hint buffer.

---

autoload/which_key.vim

This allows more arbitrary mappings, not limited by the supported values of `{ 'g:somedict' }` (e.g. local dicts, subkeys, etc.)
```vim
let s:mydict = { 'some': {} }
call which_key#register('<Space>', s:mydict.some)
```

Support passing a dict ref to `which_key#register()`

---

autoload/which_key/renderer.vim

This is the default in both spacemacs and doom emacs, which feels quite a bit more intuitive. If you don't want to break existing users' expectation, making it configurable should be trivial too.

Sort groups keys to the end

---

autoload/which_key.vim

Thanks for making this plugin! Coming back from emacs, it's one of the things I missed the most.
I was trying to use the `which_key_fallback_to_native_key` functionality with my `g` bindings and I noticed something odd.
Basically, if you get to the point that the which-key popup appears and then complete with a native command (let's say `g` ...pause... `j`) then the last character of that command will get appended to your next command that does not pause long enough for the popup to appear (let's say `gg`) so you end up with `ggj`.
My `vimscript` foo is very minimal, but conditionally appending the `fallback_cmd` `current_char` in only the case where the popup appears fixes this issue for me. I have been living with the change for a few days and have not noticed any side effects.

Native fallback appends character from previous command in certain cases

---

autoload/which_key/renderer.vim

Before:
After:
CC @BrotifyPacha

Fix the padding size of centered opt when relative win opt is on

---

autoload/which_key/window.vim

Seems to be a bug in Neovim floating windows when location list window is made non modifiable.
``` {.vimscript}
lvimgrep /.*/ %
lopen
set nomodifiable
lclose
```
It is possible to correct that bug by adding a line which let us modify the buffer before adding lines

Set modifiable buffer option before setting lines for nvim floating windows

---

doc/vim-which-key.txt

A simple fix: s/colomns/columns

Fix a spelling typo in documentation

---

autoload/which_key.vim

Fixes #177
The delay is caused by a bug in s:has_children(input) function. Where if you would supply "." as the input, it wouldn't be escaped properly. And so it would be interpreted as "any" mapping.
The fix is to add custom elseif for "." case.

Fix "." mapping delay

---

autoload/which_key/window.vim

This allow to use if &filetype == 'which_key' regardless of which kind
of window which_key is using.

Set filetype=which_key for floating window as well

---

README.md
autoload/which_key.vim

In writing a C# layer for *space-vim*, I wanted to overlap/replace/augment the '+lsp' key mappings.
**EDIT2:** For example, in *space-vim* the hotkey sequence ' lgd' is '+lsp/+goto/definition' using the existing '+lsp' keymappings using the LSP Client as configured in *space-vim*, but in *.cs files ' lgd' should use *OmniSharp-vim* (in the C# *space-vim* layer) to do the same. *OmniSharp-vim* isn't an LSP Client (it doesn't use the language server protocol (LSP)) but does many of the same things with a *language server*, so it makes sense to use the same hotkeys.
The most convenient way I thought to do this was to use a dictionary-function as an element within the *vim-which-key* description dictionary (see `:help dictionary-function`). May have pros/cons compared to the technique of …

Support Dictionary-function elements within the description dictionary

---

README.md
autoload/which_key.vim
autoload/which_key/mappings.vim
doc/vim-which-key.txt

Fixes #155.
Explanation and example of use is in my #155 comment.
**EDIT:** It is now backwards compatible with same behaviour.
If end-users want different vim-which-key descriptions in visual mode they'll need to register a description-dictionary for each prefix key and each mode.
```vim
call which_key#register('<Space>', 'g:desc', 'n')
call which_key#register('<Space>', 'g:desc_visual', 'v')
```
If they want the same behaviour as before (one dictionary for both normal and visual modes) they don't have to change anything:
```vim
call which_key#register('<Space>', 'g:desc')
```

Add visual mode separate description dictionary

---

autoload/which_key.vim
autoload/which_key/char_handler.vim

Rather than list specific cases `<Tab>` `<Space>`, I think it better to generalize.
This PR proposes a way to generalize the mapping of keycodes to internal data-structures (description dictionary, native cache).
Also a couple other improvements:
1. Improved regex escaping in s:has_children()
2. Improved loop in s:wait_with_timeout(), there was a 20ms window before the timeout where if the user pressed a key in that timespan it would be considered not pressed.

Improve keycode merging

---

autoload/which_key/mappings.vim

i think this is a reasonable compromise, since 1) i think this code is just trying to get the actual mapping so it can show something in the which key menu if the user hasn't supplied a description, 2) there isn't anything useful to display in the case of a Lua implementation, and 3) if we don't ignore these, i'm getting errors like the following in neovim 0.9.0:
```
Error detected while processing function which_key#start[26]..<SNR>35_cache_key[4]..which_key#mappings#parse:
line   25:
E716: Key not present in Dictionary: "rhs])"
E116: Invalid arguments for function call
line   34:
E716: Key not present in Dictionary: "rhs, '<SID>', '<SNR>'.mapd['sid'].'_', 'g')"
E116: Invalid arguments for function substitute
```
thank you for the fantastic plugin. 🙇

do not parse mappings with lua implementations

---

autoload/which_key.vim
autoload/which_key/mappings.vim
autoload/which_key/renderer.vim
autoload/which_key/window.vim

1. Comparable with legacy vim  by adding missing functions when `has('lambda')`, `execute()` not exist
2. Support nvim builtin-in lua function by parse from runtime lua  script.

Comparable with legacy vim, and show nvim lua built funtion

---

autoload/which_key/mappings.vim

Update workaround for default <leader><leader> EasyMotion prefix to only apply when `<leader><space>` is actually mapped to an EasyMotion action.
This allows other `<leader><space>` mappings to automatically show up in the WhichKey menu, without being explicitly added to the dictionary.
Note: I use `<leader><space>` to toggle showing white space characters
Partial fix for #135 (does not fix `<leader><tab>`, only `<leader><space>`)

Automatically show <Space> mappings in menu

---

autoload/which_key.vim

The mapping `<Tab>` is tracked in the mappings in String form, while the returned value from `getchar()` is a Number, convert it to String manually so that the corresponding entry in `s:runtime` can be retrieved.
Close #135

Handle special keys in the mapping properly

---

autoload/which_key.vim

Restore code to clear cached keys when g:which_key_run_map_on_popup = 1
This appears to have been accidentally deleted in commit 654dfc15
Fixes #242

Fix buffer local maps / option to disable caching

---

autoload/which_key/char_handler.vim

Only `key` and `val` are legal according to `:h map()`.
Close #244
cc @rene-descartes2021

Fix lambda in map()
